apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: app
  name: app
spec:
  selector:
    matchLabels:
      io.kompose.service: app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yaml convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: DATABASE_HOST
              value: db
            - name: DATABASE_NAME
              value: api
            - name: DATABASE_PASSWORD
              value: api
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              value: api
            - name: FLASK_APP
              value: app
            - name: FLASK_DEBUG
              value: "true"
            - name: FLASK_ENV
              value: development
            - name: HOST
              value: db
            - name: PORT
              value: "8000"
          image: mmbatteries/app:latest
          name: app
          ports:
            - containerPort: 5000
              protocol: TCP
          volumeMounts:
            - mountPath: ./flask_app
              name: app-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: app-cm0
          name: app-cm0
