version: "3.8"
networks:
  network:
    driver: bridge
services:
  db:
    image: mmbatteries/db:latest
    restart: always
    env_file: ./.env
    environment:
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_NAME=$DATABASE_NAME
    container_name: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DATABASE_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgres
  app:
    depends_on:
      db:
        condition: service_healthy
    image: mmbatteries/app:latest
    restart: always
    environment: 
      - DATABASE_NAME=$DATABASE_NAME
      - HOST=$DATABASE_HOST
      - DATABASE_USER=$DATABASE_USER
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_HOST=$DATABASE_HOST
      - FLASK_ENV=$FLASK_ENV
      - FLASK_APP=$FLASK_APP
      - FLASK_DEBUG=$FLASK_DEBUG
      - DATABASE_PORT=$DATABASE_PORT
      - PORT=$PORT
    volumes:
     - ./flask_app:/app/
    ports:
      - "5000:5000"
  nginx:
    image: nginx:latest
    ports: 
    - "80:80"
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        bind:
          create_host_path: true
    depends_on:
     - app
volumes:
  db:
  app:
  nginxVolume: