apiVersion: v1
data:
  nginx.conf: |+
    events {}
    http {
        server {
            listen 80;
            location / {
                proxy_pass http://app:5000;
            }
        }
    }

kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: nginx
  name: nginx-cm0
